apiVersion: v1
data:
# {{ .Values.settings.custom_monitor_glob }}
{{- $globbed_custom_monitors := .Files.Glob (default "" .Values.settings.custom_monitor_glob) }}
# {{ $globbed_custom_monitors }}
{{- range $path, $_ := $globbed_custom_monitors }}
  {{ $path | base }}: |
    {{- $.Files.Get $path | nindent 4 }}
{{- end }}
{{- if .Values.settings.custom_monitor_definitions }}
  {{ .Values.settings.custom_monitor_definitions | toYaml | nindent 2 }}
{{- end }}
{{- if and (not $globbed_custom_monitors) (not .Values.settings.custom_monitor_definitions)  }}
  {}
{{- end }}
kind: ConfigMap
metadata:
  name: {{ include "node-problem-detector.customConfig" . }}
  labels:
    app.kubernetes.io/name: {{ include "node-problem-detector.name" . }}
    helm.sh/chart: {{ include "node-problem-detector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
